services:
  postgres_db:
    image: postgres:16
    container_name: crm_db
    env_file:
      - src/.env
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__POSTGRES_USER}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__POSTGRES_PASSWORD}"
      POSTGRES_DB: "${APP_CONFIG__DB__POSTGRES_DB}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d srm_db" ]
      timeout: 5s
      interval: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: crm_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/postgresql/rabbitmq


volumes:
  postgres_data:
  rabbitmq_data: